language:
  - python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

before_install:
  - sudo add-apt-repository https://github.com/FFTW/fftw3.git
  - git status
  - sudo apt-get install libfftw3

  - sh bootstrap.sh
  - make

install:
  - pip install -r requirements.txt


before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - export CC=${C_COMPILER}

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/build
  #- pep8 test/test.py
  - py.test -vv test/test.py

notifications:
  email: false