language:
  - python

python:
  - 2.6

before_install:
  - sudo apt-get install fftw3

install:
  - pip install -r requirements.txt

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - PROJECT_BUILD_DIR=$PWD/build PROJECT_INCLUDE_DIR=$PWD/api PYTHONPATH=$PWD/api py.test test/test.py

notifications:
  email: false
