language:
  - python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install:
  - pip install -r requirements.txt
  - pip install pyfftw3

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - export CC=${C_COMPILER}

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/build
  #- pep8 test/test.py
  - py.test -vv test/test.py

notifications:
  email: false